import { Request, Response, NextFunction } from 'express';

const catchAsyncError = (fn: (req: Request, res: Response, next: NextFunction) => any) => {
  return (req: Request, res: Response, next: NextFunction) => {
    fn(req, res, next).catch((err: any) => next(err));
  };
};

export { catchAsyncError };